### ISSUE TITLE
base58 implementation seems to be incorrect

### ISSUE THREAD

**Issue by deontologician** [chronark/libs#7]
Hey, I haven't looked at your code in detail, but there seems to be an issue with the base58 implementation. I was getting lots of collisions with low numbers of ids. Switching to `base-X` and using the same library string you have in this library fixed it.

**Comment by chronark** [comment]
Hey @deontologician,
you are probably right and my implementation is wrong.

I released v0.3.8 with the base-x implementation

**Comment by deontologician** [comment]
Thanks! (and also thanks for the making this library, it's really nice)
